data:
  build: data
  hostname: data

postgres:
  image: postgres:latest
  hostname: postgres
  environment:
    - CKAN_SQLALCHEMY_URL=postgresql://ckan_default:pass@postgres:5432/ckan_default
    - CKAN_DATASTORE_WRITE_URL=postgresql://ckan_default:pass@postgres:5432/datastore_default
    - CKAN_DATASTORE_READ_URL=postgresql://datastore_default:pass@postgres:5432/datastore_default
  volumes:
    - ./postgres/create_ckan_database_objects.sh:/docker-entrypoint-initdb.d/create_ckan_database_objects.sh
    - ./postgres/setup_remote_connections.sh:/docker-entrypoint-initdb.d/setup_remote_connections.sh

solr:
  image: solr:latest
  hostname: solr
  volumes:
    - ./solr/ckan:/opt/solr/server/solr/ckan

datapusher:
  build: datapusher
  hostname: datapusher

ckan:
  build: .
  hostname: ckan
  ports:
    - "8000:8000"
  links:
    - postgres:postgres
    - solr:solr
    - datapusher:datapusher
  volumes_from:
    - data
  volumes:
    - ./setup/production.ini:/srv/app/production.ini
  environment:
    - CKAN_SQLALCHEMY_URL=postgresql://ckan_default:pass@postgres:5432/ckan_default
    - CKAN_DATASTORE_WRITE_URL=postgresql://ckan_default:pass@postgres:5432/datastore_default
    - CKAN_DATASTORE_READ_URL=postgresql://datastore_default:pass@postgres:5432/datastore_default
