version: '2'

services:
  mongo:
    image: mongo:${MONGO_VERSION}
    command: --nojournal
  orion:
    image: fiware/orion:${ORION_VERSION}
    links:
      - mongo
    ports:
      - "1026:1026"
    command: -dbhost mongo
