.catalog:
  name: "Orion"
  version: "1.0"
  description: "Orion Fiware"
  uuid: orion-1.0
  minimum_rancher_version: v0.56.0

mongo:
  scale: 3
  health_check:
    port: 27017
    interval: 5000
    unhealthy_threshold: 3
    request_line: ''
    healthy_threshold: 2
    response_timeout: 5000

orion:
  scale: 3
  health_check:
    port: 1026
    interval: 5000
    unhealthy_threshold: 3
    request_line: ''
    healthy_threshold: 2
    response_timeout: 5000
