version: '2'

services:
  device-simulator:
    image: fiware/device-simulator
    external_links:
      - orion/orion:orion
      - orion/mongo:mongo
      - mosquitto/mosquitto:mosquitto
      - iotagent/iotagent:iotagent
    command: sleep infinity
